/*
 * <copyright>
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the Cougaar Open Source License as published by
 *  DARPA on the Cougaar Open Source Website (www.cougaar.org).
 *
 *  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 *  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 *  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 *  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 *  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 *  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 *  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *  PERFORMANCE OF THE COUGAAR SOFTWARE.
 * </copyright>
 */

package org.cougaar.community;

import org.cougaar.core.service.community.*;

import org.cougaar.core.blackboard.Publishable;


/** CommunityServiceResponse Interface
  * A CommunityServiceResponse is a direct response to a method invoked on
  * the CommunityService.  The CommunityService method call that
  * corresponds to this response may be determined by its
  * UID.  The result of the request is provided by a result code.  In some
  * cases the request may also generate an object which is returned
  * with the response and is accessed using the getResponseObject method.
  **/

public class CommunityResponseImpl implements
  CommunityResponse, java.io.Serializable {

  private int resultCode = CommunityResponse.FAIL;
  private String resultMessage = null;
  private Object responseObject = null;

  /**
   * Constructor.
   */
  public CommunityResponseImpl(int resCode, String resMsg,
      Object resObj) {
    this.resultCode = resCode;
    this.resultMessage = resMsg;
    this.responseObject = resObj;
  }


  /**
   * The getResultCode method returns the status of the CommunityService
   * request.
   * @return Verb  Returns the ResultCode of the CommunityService request
   **/
  public int getResultCode() {
    return this.resultCode;
  }


  /**
   * The getResultMessage method returns any detailed message that may
   * be associated with the notification.  For instance, if the result code
   * is ERROR, this method will return an error message to assist in debugging.
   * @return  Returns a message with details associated with the result code
   **/
  public String getResultMessage() {
    return this.resultMessage;
  }


  /**
   * The getResponseObject method returns any object that may have been
   * generated by the CommunityService request.
   * @return  Returns request specific object
   **/
  public Object getResponseObject() {
    return this.responseObject;
  }

  /**
   * Sets the response object.
   **/
  public void setResponseObject(Object obj) {
    this.responseObject = obj;
  }

  protected static String resultCodeToString(int code) {
    if (code == CommunityResponse.ERROR) return "ERROR";
    if (code == CommunityResponse.SUCCESS) return "SUCCESS";
    if (code == CommunityResponse.FAIL) return "FAIL";
    if (code == CommunityResponse.GRANT) return "GRANT";
    if (code == CommunityResponse.DENY) return "DENY";
    return "ILLEGAL_VALUE";
  }

  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append("code=" + resultCodeToString(resultCode) +
      ", message=\"" + resultMessage + "\"" +
      ", objectClass=" +
      (responseObject == null ? "null" : responseObject.getClass().getName()));
    return sb.toString();
  }

  public boolean isPersistable() { return true; }
}